services:
  qguardarr:
    image: ghcr.io/mrinvincible29/qguardarr:latest
    container_name: qguardarr
    user: "${UID:-1000}:${GID:-1000}"
    ports:
      - "${APP_PORT:-8089}:${APP_PORT:-8089}"
    volumes:
      - ./config:/app/config:ro
      - ./data:/app/data
      - ./logs:/app/logs
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      # qBittorrent connection
      # On Mac/Windows: use host.docker.internal instead of localhost
      - QBIT_HOST=${QBIT_HOST:-host.docker.internal}
      - QBIT_PORT=${QBIT_PORT:-8080}
      - QBIT_USERNAME=${QBIT_USERNAME:-admin}
      - QBIT_PASSWORD=${QBIT_PASSWORD}
      - APP_PORT=${APP_PORT:-8089}
      
      # Cross-seed integration (optional)
      # On Mac/Windows: use host.docker.internal instead of localhost
      - CROSS_SEED_URL=${CROSS_SEED_URL:-http://host.docker.internal:2468/api/webhook}
      - CROSS_SEED_API_KEY=${CROSS_SEED_API_KEY}
      
      # Python settings
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app
    
    # Resource limits (adjust via MEM_LIMIT)
    mem_limit: ${MEM_LIMIT:-256m}
    cpus: 0.1
    
    # Restart policy
    restart: unless-stopped
    
    # Health check
    healthcheck:
      test: ["CMD", "python", "-c", "import os,httpx; httpx.get('http://localhost:' + os.environ.get('APP_PORT','8089') + '/health')"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    
    # Logging
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  default:
    name: qguardarr-network
